src/towncrier/__init__.py, src/towncrier/_builder.py, src/towncrier/_git.py, src/towncrier/_settings.py
Instead of ``<package>/<section>/<newsfragments>`` being the only real option, this allows instead to define your own top level news fragment directory. This could be something like ``./news`` and then inside of that directory there is either news fragments directly, or sub directories for different sections.
Fixes #24
=> WIP: Allow a configurable directory instead of using package layout

src/towncrier/_settings.py
Even if toml error reporting is far from perfect,
if you have a syntax error in your toml, you want to be informed
rather than switching to .ini parsing
=> dont swallow the toml parsing exception

src/towncrier/_builder.py, src/towncrier/newsfragments/62.feature, src/towncrier/test/test_cli.py
Now you can name fragments like 123.feature.rst, to make your editor
happy.
Fixes gh-62.
=> Ignore extensions on fragment filenames

src/towncrier/_builder.py, src/towncrier/newsfragments/70.feature, src/towncrier/templates/template.rst, src/towncrier/test/test_cli.py, src/towncrier/test/test_format.py, src/towncrier/test/test_write.py
=> Make section and type output match the config file order.

src/towncrier/__init__.py, src/towncrier/_builder.py, src/towncrier/_git.py, src/towncrier/newsfragments/101.bugfix, src/towncrier/newsfragments/99.bugfix, src/towncrier/test/test_cli.py, src/towncrier/test/test_format.py, src/towncrier/test/test_write.py
This still needs tests, but it fixes #99 and ameliorates #101 well enough to
let me generate some actual release notes. It also adds some better
error checking. (Each commit is self-contained.)
As noted in #101, it probably would be better if towncrier had a
configuration option specifying what filename extension to use,
instead of blindly accepting all extensions. That would have been
cleverer of me. I think all these changes are probably still useful
in their own right though.
=> Several fixes to newsfragment extension handling

src/towncrier/__init__.py
I was wondering if this is possible but did not see the option with `towncrier --help`. I tried it anyway, saw that it works and came here to tell the world about it :)
=> Add help entry for --version

src/towncrier/__init__.py, src/towncrier/test/test_cli.py
I found that:
> It is usable by projects written in other languages, provided you give it the version of the project when invoking it.
Was not the case, as towncrier wanted to load a Python package in order to get the project name.
I've added another cli option to ignore that behaviour, in the same way as the version does. It now works in non-python projects 🌐
=> make project name configurable from cli

src/towncrier/__init__.py, src/towncrier/_settings.py, src/towncrier/newsfragments/111.feature, src/towncrier/test/test_cli.py
When the version is passed on the command line, and the `title_format` does not use the package name, and it is not used for the path to the news fragments, then no package name is needed, so we should not enforce it.
Closes issue #111.
=> Made `package` optional.

src/towncrier/_settings.py, src/towncrier/check.py, src/towncrier/newsfragments/123.feature, src/towncrier/test/test_check.py
Allows for a work-around for #123
=> Add a --pyproject option to towncrier.check

src/towncrier/_builder.py, src/towncrier/newsfragments/119.feature, src/towncrier/test/test_format.py, src/towncrier/test/test_write.py
This extends the fragment format to be `<issue>.<type>(.<counter>)` i.e have an optional `.counter` after the type, which needs to be an integer.
=> Allow for multiple fragments with the same ticket and type

src/towncrier/check.py, src/towncrier/newsfragments/124.feature, src/towncrier/test/test_check.py
=> Report git's output when git fails

src/towncrier/__init__.py, src/towncrier/newsfragments/157.feature
Following on from https://github.com/hawkowl/towncrier/pull/127, this allows a custom configuration file to be specified at the command line
=> Allow specifying custom config file at the command line

src/towncrier/_builder.py, src/towncrier/newsfragments/173.feature.rst, src/towncrier/test/test_builder.py
The new version uses category as the reference point to later infer the issue number and counter value.
As a consequence, it will return `(None, None, None)` if the base name doesn't contain a valid category.
The new parser allows using file names like `123.feature.1.ext` which are convenient when one wants to use an appropriate extension (e.g. `rst`, `md`) to enable syntax highlighting.
=> Improve news fragment file name parsing

src/towncrier/__main__.py, src/towncrier/newsfragments/163.bugfix, src/towncrier/test/test_project.py
This makes the -m invocation work.
I added a test, but:
- I didn't know in what file you wanted it
- I didn't know if Trial had a way to manage the current directory
Let me know if I should change anything.
=> Fix the use of -mtowncrier. #163

src/towncrier/create.py, src/towncrier/newsfragments/275.feature, src/towncrier/test/test_create.py, tox.ini
Now, you don't have to create the news fragment and then edit it. You can write the content dynamically!
=> Users can now write the content in the "create" method.

src/towncrier/newsfragments/173.feature.rst
This resulted in an extra space of indent on the hanging lines which caused misformatting when rendered.
=> less leading spaces in 173.feature.rst

src/towncrier/_shell.py, src/towncrier/newsfragments/339.feature.rst, src/towncrier/test/test_project.py
This PR fixes #339 and adds a `--version` option. This makes it possible to run the command like this:
```
$ towncrier --version
towncrier, version 21.3.1.dev0
```
=> Provide a --version option

src/towncrier/_writer.py, src/towncrier/newsfragments/346.bugfix
Closes #346
The title is already rendered in `content`. This does not fix draft mode, but that is recorded in a separate issue.
=> Stop writing title twice when title_format is specified

README.rst, docs/configuration.rst, src/towncrier/_settings/__init__.py, src/towncrier/_settings/fragment_types.py, src/towncrier/_settings/load.py, src/towncrier/newsfragments/369.feature.rst, src/towncrier/test/test_settings.py
* Add support to toml tables for custom fragments,
with default values.
Resolves: twisted/#369
Signed-off-by: danieljmv01 <danieljmv01@gmail.com>
=> feat(settings): Add support to configure fragment types via tables

src/towncrier/create.py, src/towncrier/newsfragments/374.feature.rst, src/towncrier/test/test_create.py
Description
=======
When using `git` one can set a commit message using the `-m` flag. For example:
```
git commit -m "This is my message"
```
Taking inspiration from this, now *Towncrier* can also get a message from user using a `-m` flag:
```
towncrier create 123.feature -m "This is a message that describes the news fragment"
```
This feature plays nicely with the `--edit` flag.
=> Create message in command line

.github/workflows/ci.yml
Everything except Linux is very slow on GHA.
macOS is very similar to Linux, so we can safely drop it and it's fine to test
one CPython and one PyPy on Windows.
Saves the planet...eh... fixes #379
=> Shrink CI matrix

.github/workflows/ci.yml
This tries to work around an issue with GitHub.
We have a PR configured to allowing merging only if Job A is green.
If you have a job A depending on another job B, if job B fails, job A is skipped.
But with job A skipped, GitHub is happy and it allows the PR to be merged.
Implement the nice move from @altendky from https://github.com/Chia-Network/chia-blockchain/pull/11880/
=> Enforce PR failure based on a single job and fail the job if a dependent job was skipped.

README.rst, src/towncrier/_writer.py, src/towncrier/build.py, src/towncrier/newsfragments/391.bugfix, src/towncrier/test/test_build.py, src/towncrier/test/test_write.py
the version-already-produced error raising cannot be reached in expected single file mode like the test case in :test_write:WritingTests.test_append_at_top_with_hint
=> bugfix in _writer.py

src/towncrier/_settings/__init__.py, src/towncrier/_shell.py, src/towncrier/build.py, src/towncrier/check.py, src/towncrier/create.py, src/towncrier/newsfragments/384.doc
This tries to fixes #384
The idea is that instead of having a separate `man` file that duplicated the CLI info from the Python script, we should only have the help content in the python script.
From there, we can export it to `man` or `sphinx`.
For this PR I am using the help content from #326
-------
Debian and other distrubtion can run `click-man towncrier` to generate the man content.
click-man has more info for Debian at https://github.com/click-contrib/click-man#debian-packages
---------
The result of this PR
main commnad
```
$ towncrier --help
Usage: towncrier [OPTIONS] COMMAND [ARGS]...
Towncrier is a utility to produce useful, summarised news files for your
project. Rather than reading the Git history as some newer tools to produce
it, or having one single file which developers …
```
=> Use text from debian man pages for CLI help output.

.github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, setup.cfg, tox.ini
This is take2 for #292 
Enabled check manifest and pre-comit as part of GitHub Actions CI
We have pre-commit hook so I am not sure if this is needed.
I  tried to simplify the job and removed the job matrix.
Fixes #292
* [NA] Make sure changes are covered by existing or new tests.
* [NA] For at least one Python version, make sure local test run is green.
change and include important information. Your change will be included in the public release notes.
=> Run check-manifest and other linters via GitHub Actions.

docs/cli.rst, src/towncrier/_git.py, src/towncrier/newsfragments/357.feature.rst, src/towncrier/test/test_build.py
Before this commit, all the news fragments needed to be committed into git, or the fragments removal after building the news file would crash.
In my workflow, I add missing fragments before building the news file because I'm extracting author names from the git log, and towncrier crashes at the end of the build process.
=> Handle deletion of uncommitted news fragments
