twisted/towncrier

.coveragerc, .travis.yml, src/towncrier/__init__.py, src/towncrier/_builder.py, src/towncrier/_git.py, src/towncrier/_project.py, src/towncrier/_writer.py, src/towncrier/newsfragments/6.feature, src/towncrier/test/test_format.py, src/towncrier/test/test_settings.py, src/towncrier/test/test_write.py, tox.ini
=> Implement CI

src/towncrier/__init__.py, src/towncrier/_project.py, src/towncrier/newsfragments/3.feature, src/towncrier/test/test_project.py
=> Allow tuples in __version__

src/towncrier/__init__.py, src/towncrier/newsfragments/11.feature
=> Support release dates

NEWS.rst, README.rst, src/towncrier/_writer.py, src/towncrier/newsfragments/15.feature, src/towncrier/test/test_write.py, tox.ini
=> Support headers

README.rst, src/towncrier/newsfragments/19.doc
=> Document the manual --version switch better.

src/towncrier/__init__.py, src/towncrier/_project.py, src/towncrier/newsfragments/22.bugfix
=> Make an error message less bizarre

LICENSE, src/towncrier/__init__.py, src/towncrier/_settings.py, src/towncrier/_writer.py, src/towncrier/newsfragments/35.feature, src/towncrier/test/test_cli.py, src/towncrier/test/test_write.py
=> Allow configuration of template, magic comment and titles

src/towncrier/__init__.py
=> Decode Jinja2 template off the filesystem

pyproject.toml, src/towncrier/__init__.py, src/towncrier/_builder.py, src/towncrier/_settings.py, src/towncrier/newsfragments/52.feature, src/towncrier/newsfragments/63.feature, src/towncrier/templates/template.rst, src/towncrier/test/test_cli.py, src/towncrier/test/test_format.py, src/towncrier/test/test_settings.py, src/towncrier/test/test_write.py
These have a bunch of merge conflicts with each other, and I needed to
merge them anyway to get a version of towncrier I can use to release
my thing, so I figured I'd push the merge as an alternative PR.
If you like both of them, then merging this is a quick way to do that
and skip dealing with the conflicts again. Alternatively, we can
handle them one at a time. Just don't try to merge all three of these
:-)
=> Combination of PRs #64 and #66

src/towncrier/__init__.py, src/towncrier/_builder.py, src/towncrier/_settings.py, src/towncrier/newsfragments/63.feature, src/towncrier/templates/template.rst, src/towncrier/test/test_format.py, src/towncrier/test/test_settings.py, src/towncrier/test/test_write.py
=> New configuration option: underlines = ["=", "-", "~"]

src/towncrier/__init__.py, src/towncrier/_git.py, src/towncrier/newsfragments/56.feature, src/towncrier/test/test_cli.py
=> Add --yes option to run non-interactively

src/towncrier/_builder.py, src/towncrier/newsfragments/68.bugfix, src/towncrier/test/test_format.py
Fixes gh-68
This should probably have a test added, but I don't dare touch those
files and generate even more conflicts while gh-66 and gh-68 are
outstanding...
=> Don't break long lines mid-word or at hyphens, to avoid breaking URLs

pyproject.toml
Scheming is good, double scheming not so much.
=> Fix double scheme

src/towncrier/__init__.py
At least to me it does make no sense that the header goes to stderr and the rest to stdout.
=> draft output should go completely to stdout

bin/towncrier
This is handy for running towncrier from a checkout.
=> Make bin/towncrier work when run from other directories

.travis.yml, setup.cfg, setup.py, src/towncrier/_builder.py, src/towncrier/newsfragments/121.feature, tox.ini
=> Add Python 2.7 support

src/towncrier/_settings.py
I wanted to use the parser to parse the toml file I was loading into a little bot I am writing.
=> split the config loader into file and toml parts

src/towncrier/_builder.py, src/towncrier/newsfragments/142.bugfix, src/towncrier/test/test_builder.py, src/towncrier/test/test_cli.py
=> Accept multiple dots in filenames

.coveragerc, .gitignore, .travis.yml, README.rst, src/towncrier/_settings.py, src/towncrier/_writer.py, src/towncrier/build.py, src/towncrier/newsfragments/161.feature, src/towncrier/test/test_build.py, src/towncrier/test/test_settings.py, tox.ini
Cherry-picked from https://github.com/hawkowl/towncrier/pull/158
=> Cherrypicked changes for single-file

.github/workflows/ci.yml, tox.ini
First step of #279.
Draft for:
Followup steps:
=> Add GitHub Actions workflow for testing and checking

docs/configuration.rst
typo in configuration.rst on TableFragmentTypesLoader at line34
=> typo correction in configuration.rst

setup.py, src/towncrier/newsfragments/366.misc.rst
Update the PyPI project links from @bignose-debian
Fixes #366 
* [NA] Make sure changes are covered by existing or new tests.
* [NA] For at least one Python version, make sure local test run is green.
change and include important information. Your change will be included in the public release notes.
=> Update links based on chagnes from bignose-debian.
